### ISSUE TITLE
ui-multiple model summary

### ISSUE THREAD

**Issue by cli99** [rai-project/carml#9]

**Comment by abduld** [comment]
mostly done by https://github.com/rai-project/carml/commit/acc7b1c648ee99ae21822c5e53e1d6a6275f1e6b  , https://github.com/rai-project/carml/commit/00d9532bd59cc77ee98ffbb4fdddb57ae6a89739 , and https://github.com/rai-project/carml/commit/34ff95edda0f0c9485b50affb5926ff9a7a3273c
